config/routes.rb
Mnprograms::Application.routes.draw do
  
  resources :types
  
  resources :users, :only => [:create]
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :skip => [:sessions] do
    get 'signup' => 'registrations#new', :as => :new_user_registration
    get 'account' => 'registrations#edit', :as => :edit_user_registration
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users, :except => [:create]
  
  resources :profiles
  
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  resources :programs do

    resources :submissions do
  		resources :works
	
  		member do
  		  post :rate
		  end
  	end

    member do
      put :set_default
      get :description
      get :guidelines
      get :thankyou
    end

  end
  
  
=begin  match '/:url', :to => 'programs#show'
  match '/:url/description', :to => 'programs#description', :method => :get
  match '/:url/guidelines', :to => 'programs#guidelines', :method => :get
  match '/:url/thankyou', :to => 'programs#thankyou', :method => :get
=end  
  
  root :to => "programs#index"

end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :submission_id, :type_id, :title, :link, :image, :image_cache
  
  mount_uploader :image, ImageUploader
  
  belongs_to :submission
  belongs_to :type
  
  validates :title, :presence => true
  # validates_size_of :image, :maximum => 2000000, :message => "The image file is too big, it must be smaller than 2 MB!"
  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  load_resource :submission
  load_resource :work, :through => :submission, :shallow => true
  
  def index
  end

  def show
    render :layout => 'program'
  end

  def new
    render :layout => 'program'
  end

  def create
    if @work.save
      redirect_to @work, :notice => "Successfully created work."
    else
      render :action => 'new'
    end
  end

  def edit
    render :layout => 'program'
  end

  def update
    if @work.update_attributes(params[:work])
      redirect_to @work, :notice  => "Successfully updated work."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @work.destroy
    redirect_to works_url, :notice => "Successfully destroyed work."
  end
  
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for [@submission, @work], :html => { :multipart => true }, :validate => true do |f| %>
	<%= f.error_messages %>
	
	<%= f.hidden_field :submission_id, :value => @submission.id %>

	<div class="work_type">
		<%= f.label :type_id, "Type" %> 
		<%= f.collection_select :type_id, Type.all, :id, :title %>
	</div>
	
	<div class="work_title">
		<%= f.label :title %> 
		<%= f.text_field :title %>
	</div>

	<div class="work_link">
		<%= f.label :link %> 
		<%= f.text_field :link %>
	</div>

	<div class="work_image">
		<%= f.label :image %> 
		<%= f.file_field :image %>
		<%= f.hidden_field :image_cache %>
	</div>
	
	<p><%= f.submit %></p>
	
<% end %>

app/views/works/edit.html.erb
<% title link_to(@program.title, named_program_path(@program)) %>

<% content_for :navbar do %>
	<%= render 'layouts/navbar' %>
<% end %>

<h3>Add Work</h3>

<%= render 'form' %>

<p>
  <%= link_to "Show", @work %> |
  <%= link_to "View All", works_path %>
</p>

app/views/works/index.html.erb
<% title link_to(@program.title, named_program_path(@program)) %>

<% content_for :navbar do %>
	<%= render 'layouts/navbar' %>
<% end %>

<h3>Works</h3>

<table>
  <tr>
    <th>Submission</th>
    <th>Type</th>
    <th>Title</th>
    <th>Link</th>
  </tr>
  <% for work in @works %>
    <tr>
      <td><%= work.submission_id %></td>
      <td><%= work.type %></td>
      <td><%= work.title %></td>
      <td><%= work.link %></td>
      <td><%= link_to "Show", submission_work_path(:submission) %></td>
      <td><%= link_to "Destroy", work, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Works", new_submission_work_path(@program.url, @submission) %></p>

app/views/works/new.html.erb
<% title link_to(@program.title, named_program_path(@program)) %>

<% content_for :navbar do %>
	<%= render 'layouts/navbar' %>
<% end %>

<h3>Add Work</h3>

<%= render 'form' %>

<p><%= link_to "Back", :back %></p>

app/views/works/show.html.erb
<% title "Work" %>

<p>
  <strong>Submission:</strong>
  <%= @work.submission_id %>
</p>
<p>
  <strong>Type:</strong>
  <%= @work.type %>
</p>
<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>
<p>
  <strong>Url:</strong>
  <%= @work.url %>
</p>

<p>
  <%= link_to "Edit", edit_work_path(@work) %> |
  <%= link_to "Destroy", @work, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", works_path %>
</p>