config/routes.rb
Mnprograms::Application.routes.draw do
  
  resources :types
  
  resources :users, :only => [:create]
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :skip => [:sessions] do
    get 'signup' => 'registrations#new', :as => :new_user_registration
    get 'account' => 'registrations#edit', :as => :edit_user_registration
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users, :except => [:create]
  
  resources :profiles
  
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  resources :programs do

    resources :submissions do
  		resources :works
	
  		member do
  		  post :rate
		  end
  	end

    member do
      put :set_default
      get :description
      get :guidelines
      get :thankyou
    end

  end
  
  
=begin  match '/:url', :to => 'programs#show'
  match '/:url/description', :to => 'programs#description', :method => :get
  match '/:url/guidelines', :to => 'programs#guidelines', :method => :get
  match '/:url/thankyou', :to => 'programs#thankyou', :method => :get
=end  
  
  root :to => "programs#index"

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  
  load_and_authorize_resource
  
  def index
  end

  def new
  end

  def create
    if @type.save
      redirect_to types_url, :notice => "Successfully created type."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @type.update_attributes(params[:type])
      redirect_to types_url, :notice  => "Successfully updated type."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @type.destroy
    redirect_to types_url, :notice => "Successfully destroyed type."
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for @type, :validate => true do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/types/edit.html.erb
<% title "Edit Type" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @type %> |
  <%= link_to "View All", types_path %>
</p>

app/views/types/index.html.erb
<% title "Types" %>

<table>
  <tr>
    <th>Title</th>
  </tr>
  <% for type in @types %>
    <tr>
      <td><%= type.title %></td>
	  <td>
	      <%= link_to "Edit", edit_type_path(type) %> | 
	      <%= link_to "Destroy", type, :confirm => 'Are you sure?', :method => :delete %>
	  </td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Type", new_type_path %></p>

app/views/types/new.html.erb
<% title "New Type" %>

<%= render 'form' %>

<p><%= link_to "Back to List", types_path %></p>