config/routes.rb
Mnprograms::Application.routes.draw do
  
  resources :types
  
  resources :users, :only => [:create]
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :skip => [:sessions] do
    get 'signup' => 'registrations#new', :as => :new_user_registration
    get 'account' => 'registrations#edit', :as => :edit_user_registration
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users, :except => [:create]
  
  resources :profiles
  
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  resources :programs do

    resources :submissions do
  		resources :works
	
  		member do
  		  post :rate
		  end
  	end

    member do
      put :set_default
      get :description
      get :guidelines
      get :thankyou
    end

  end
  
  
=begin  match '/:url', :to => 'programs#show'
  match '/:url/description', :to => 'programs#description', :method => :get
  match '/:url/guidelines', :to => 'programs#guidelines', :method => :get
  match '/:url/thankyou', :to => 'programs#thankyou', :method => :get
=end  
  
  root :to => "programs#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_adminbar.html.erb
<% if user_signed_in? && current_user.role?('admin') %>
	<div id="admin_toolbar">
	
		<ul id="admin_tools">
			<% if can? :create, Program %>
				<li><%= link_to "New Program", new_program_path %></li>
			<% end %>
			<% if can? :create, User %>
				<li><%= link_to "New User", new_user_path %></li>
			<% end %>
		</ul>
	
		<ul id="admin_pages">
			<% if can? :read, @programs %>
				<li><%= link_to 'Programs', programs_path %></li>
			<% end %>
			<% if can? :read, @users %>
				<li><%= link_to 'Users', users_path %></li>
			<% end %>
		</ul>
	
	</div>
<% end %>

app/views/layouts/_loginbar.html.erb
<div id="user_nav">
	<% if user_signed_in? %>
		Signed in as <%= link_to current_user.email, edit_user_registration_path(current_user) %> | 
		<%= link_to "Profile", edit_profile_path(current_user.profile) %> | 
		<%= link_to "Sign out", destroy_user_session_path %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %> or Sign in via: 
		<%= link_to 'Google', '/auth/google' %> or 
		<%= link_to 'Facebook', '/auth/facebook' %>
	<% end %>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar">
	
	<ul id="tools">
		<% if can? :read, @program.submissions %>
			<% if @program.submissions.count > 0 %>
				<li><%= link_to "View " + @program.submissions.count.to_s + " Submissions", program_submissions_path(@program), :id => 'view_submissions_link' %></li>
			<% else %>
				<li><p class="toolbar">There are no submmissions</p></li>
			<% end %>
		<% end %>
	
		<% if (can? :create, Submission) && !current_user.submission(@program) %>
			<li><%= link_to "Submit Your Work", new_program_submission_path(@program), :id => 'new_work_button' %></li>
		<% end %>
		
		<% if current_submission(@program) && (can? :update, current_submission(@program)) %>
			<li><%= link_to 'Edit Your Submission', edit_program_submission_path(@program, current_submission(@program)), :id => 'edit_work_button' %></li>
		<% end %>
		
		<% if !user_signed_in? %>
			<li><p class="toolbar">You must create an account or sign in to submit your work.</p></li>
		<% end %>
	</ul>
	
	<ul id="pages">
		<li><%= link_to 'Home', program_path(@program) %></li>
		<li><%= link_to 'Description', description_program_path(@program) %></li>
		<li><%= link_to 'Guidelines', guidelines_program_path(@program) %></li>
	</ul>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : APP_CONFIG['site_name'] %></title>
    <%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "jquery-ui-themes/hot-sneaks/jquery-ui-1.8.13.custom" %>
	
	<%= javascript_include_tag :defaults, "rails.validations", "rails.validations.custom", 'jquery-ui-1.8.13.custom.min' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
		
		<%= render 'layouts/loginbar' %>
		
		<div id="header">
			<% if show_title? %>
				<%=h content_tag :h1, yield(:title) %>
			<% else %>
				<%=h content_tag :h1, link_to(APP_CONFIG['site_name'], root_url) %>
			<% end %>
		</div>
		
		<%= render 'layouts/adminbar' %>
		
		<%= yield(:navbar) %>
			
		<% flash.each do |name, msg| %>
			<div id="flash_<%= name %>">
				<%= msg %> <a id="close_link">close</a>
			</div>
		<% end %>
      	
		<%= yield %>
		
		<div id="footer">
			<div id="footer_inner">
				<%= yield(:footer) %>
			</div>
		</div>
		
    </div>
  </body>
</html>

app/views/layouts/program.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : APP_CONFIG['site_name'] %></title>
    <%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "jquery-ui-themes/hot-sneaks/jquery-ui-1.8.13.custom" %>
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans' rel='stylesheet' type='text/css'>
	<%= ajaxful_rating_style %>
    
	<%= javascript_include_tag :defaults, "rails.validations", "rails.validations.custom", 'jquery-ui-1.8.13.custom.min' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
		
		<%= render 'layouts/loginbar' %>
		
		<%= content_tag :h1, yield(:title) if show_title? %>
		
		<%= render 'layouts/adminbar' %>
		
		<%= yield(:navbar) %>
			
		<% flash.each do |name, msg| %>
			<div id="flash_<%= name %>">
				<%= msg %> <a id="close_link">close</a>
			</div>
		<% end %>
      
		<div id="content">
			<div id="content_inner">
				<%= yield %>
			</div>
		</div>
		
		<div id="footer">
			<div id="footer_inner">
				<%= yield(:footer) %>
			</div>
		</div>
		
    </div>
  </body>
</html>